/** Shared API contract types (scaffold — OpenAPI generation comes later). */

export {
  hasAnyPermission,
  hasPermissions,
  resolvePermissions,
} from "./auth.js";
export type {
  AuthErrorResponse,
  AuthMessageResponse,
  AuthTokensResponse,
  ForgotPasswordRequest,
  GlobalRole,
  LeagueRole,
  LeagueSummary,
  LoginRequest,
  Permission,
  PermissionContext,
  RefreshRequest,
  RegisterRequest,
  ResendVerificationRequest,
  ResetPasswordRequest,
  SessionUser,
  VerifyEmailRequest,
} from "./auth.js";

export {
  PROFILE_LANGUAGE_OPTIONS,
  PROFILE_TIMEZONE_OPTIONS,
} from "./profile.js";
export type {
  PolicyConsentRequest,
  UpdateProfileRequest,
  UserProfile,
  UserType,
} from "./profile.js";

export {
  DELETE_ACCOUNT_CONFIRMATION_PHRASE,
} from "./privacy.js";
export type {
  AccountDataExport,
  DeleteAccountRequest,
  PrivacyMessageResponse,
} from "./privacy.js";

export type {
  AcceptedLeagueInvite,
  AcceptLeagueInviteRequest,
  CompetitionSummary,
  CreatedLeagueInvite,
  CreateLeagueInviteRequest,
  CreateLeagueRequest,
  FantasyRole,
  FantasyRosterSlot,
  FantasyTeam,
  FantasyTeamSummary,
  EnsureFantasyTeamsResult,
  RosterComposition,
  RosterCompositionCounts,
  RosterCompositionIssue,
  RosterCompositionLimits,
  RosterCompositionStatus,
  AssignRosterSlotRequest,
  RosterOccupancyEntry,
  CreditAccount,
  CreditLedgerEntry,
  CreditLedgerList,
  CreditLedgerReason,
  AdminCreditMovementRequest,
  RosterImportAthleteCandidate,
  RosterImportConfirmRequest,
  RosterImportConfirmResult,
  RosterImportIssue,
  RosterImportPreview,
  RosterImportResolution,
  RosterImportRow,
  RosterImportRowStatus,
  RosterImportStatus,
  RosterOwnershipSource,
  RosterOwnershipInterval,
  RosterOwnershipHistory,
  RosterAsOfSlot,
  RosterAsOf,
  CreateRosterTurnSnapshotRequest,
  RosterTurnSnapshotSummary,
  RosterTurnSnapshotEntry,
  RosterTurnSnapshotDetail,
  LeagueAdminPanel,
  LeagueCalendar,
  LeagueCalendarFormat,
  LeagueCalendarMatchup,
  LeagueCalendarRound,
  LeagueCalendarStatus,
  LeagueDetail,
  LeagueInvite,
  LeagueInviteStatus,
  LeagueLifecycle,
  LeagueLifecycleBlocker,
  LeagueListoneEntry,
  LeagueListoneOverride,
  LeagueListoneRefreshCounters,
  LeagueListoneRefreshJob,
  LeagueListoneRefreshProgress,
  LeagueListoneRefreshResult,
  LeagueMember,
  LeagueRules,
  LeagueRulesOptions,
  LeagueRosterConfig,
  LeagueState,
  TransitionLeagueStateRequest,
  UpdateLeagueRulesRequest,
  CreateNamedLeagueInviteRequest,
  FantasyCoachDirectoryItem,
  NamedLeagueInvite,
  NamedLeagueInviteStatus,
  PaginatedFantasyCoachDirectory,
  RespondedNamedLeagueInvite,
} from "./leagues.js";

export {
  computeCutoff,
  deriveEffectiveStatus,
  isModificationAllowed,
  applyCutoffRecalculation,
  kickoffCountsForCutoff,
  mapFixtureMatchStatus,
  reconcileFixtureKickoffLock,
} from "./fantasyTurns.js";
export type {
  ExcludeFantasyTurnFixtureRequest,
  FantasyFixtureMatchStatus,
  FantasyRoundFixtureReason,
  FantasyTurnDetail,
  FantasyTurnFixture,
  FantasyTurnKind,
  FantasyTurnPreview,
  FantasyTurnStatus,
  FantasyTurnSummary,
  GenerateFantasyTurnRequest,
  KickoffLockState,
} from "./fantasyTurns.js";

export type {
  CopyLineupResult,
  FantasyModule,
  LineupContext,
  LineupDraft,
  LineupEvaluation,
  LineupIssue,
  LineupPlayer,
  LineupPlayerInput,
  LineupRole,
  LineupRosterPlayer,
  LineupSlotKind,
  LineupSubstitution,
  ModuleCounts,
  PreviousLineupSummary,
  SaveLineupDraftRequest,
  SaveLineupRequest,
  SavedLineup,
  SubstitutionResolution,
  TacticalMoveEvaluation,
  TacticalMoveStatus,
  TacticalMoveSummary,
} from "./fantasyLineups.js";
export {
  APPROVED_MODULES,
  MAX_AUTOMATIC_SUBSTITUTIONS,
  MAX_TACTICAL_MOVES,
  approvedModuleCatalog,
  copyPreviousLineup,
  evaluateBenchOrderLock,
  evaluateLineup,
  evaluateProgressiveLock,
  evaluateTacticalMove,
  isApprovedModule,
  isAthleteKickoffLocked,
  isLineupModificationAllowed,
  isTacticalWindowActive,
  lineupSignature,
  moduleCounts,
  moveBenchItem,
  moveBenchToIndex,
  orderedBenchFromRoster,
  preserveLockedStarters,
  remainingRosterForBench,
  remainingTacticalMoves,
  resolveAutomaticSubstitutions,
  slotsFromLineupIds,
  starterTemplate,
} from "./fantasyLineups.js";

export type {
  CounterTradeProposalRequest,
  CreateMarketSessionRequest,
  CreateTradeProposalRequest,
  MarketBid,
  MarketBidList,
  MarketBidStatus,
  MarketHistoryCategory,
  MarketHistoryEntry,
  MarketHistoryFilters,
  MarketHistoryList,
  MarketReleasePreview,
  MarketReleaseReason,
  MarketReleaseRequest,
  MarketReleaseResult,
  MarketResolution,
  MarketResolutionOutcome,
  MarketResolutionOutcomeKind,
  MarketSession,
  MarketSessionKind,
  MarketSessionStatus,
  SubmitMarketBidRequest,
  TradeAthlete,
  TradeProposal,
  TradeProposalList,
  TradeStatus,
} from "./market.js";

export type { BreadcrumbItem, NavItemDefinition, NavSurface } from "./navigation.js";

export {
  ALL_MACROFLOWS,
  WIREFRAME_CATALOG,
  WIREFRAME_STATES,
  getWireframeScreen,
  macroflowsCovered,
  parseWireframeState,
} from "./wireframes.js";
export type {
  Macroflow,
  WireframeScreenId,
  WireframeScreenMeta,
  WireframeUiState,
} from "./wireframes.js";

export {
  SERVICES,
  type HealthResponse,
  type HealthStatus,
  type ServiceId,
  type ServiceInfo,
} from "./health.js";

export type {
  AdminLeague,
  AdminListoneEntry,
  AdminListoneRefreshCounters,
  AdminListoneRefreshJob,
  AdminListoneRefreshProgress,
  AdminListoneRefreshResult,
  AdminOverview,
  AdminUser,
  PaginatedAdminLeagues,
  PaginatedAdminUsers,
  PlatformRole as AdminPlatformRole,
} from "./admin.js";
