import { lazyStyles } from "../../theme/lazyStyles";
import { theme } from "@fantappero/ui/theme";
import { StyleSheet } from "react-native";

const { colors, spacing, typography, radius } = theme;

export const rosterStyles = lazyStyles(() => StyleSheet.create({
  summary: {
    fontSize: typography.fontSize.md,
    color: colors.foreground,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontSize: typography.fontSize.sm,
    color: colors.muted,
    marginTop: -spacing.xs,
    marginBottom: spacing.sm,
  },
  fieldLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.muted,
    marginBottom: spacing.xs,
  },
  meta: {
    fontSize: typography.fontSize.sm,
    color: colors.muted,
    marginBottom: spacing.sm,
  },
  compositionBox: {
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  errorText: {
    fontSize: typography.fontSize.sm,
    color: colors.danger,
  },
  roleTables: {
    gap: spacing.md,
  },
  roleSection: {
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  roleSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  roleSectionTitle: {
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    color: colors.foreground,
    flex: 1,
  },
  roleSectionCount: {
    fontSize: typography.fontSize.sm,
    color: colors.muted,
  },
  credits: {
    marginBottom: spacing.sm,
    gap: spacing.xs,
  },
  creditsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  creditsBalance: {
    flex: 1,
    fontSize: typography.fontSize.sm,
    color: colors.foreground,
  },
  creditsButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.background,
  },
  creditsButtonLabel: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.foreground,
  },
  adjustBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  adjustBackdropTap: {
    flex: 1,
  },
  adjustSheet: {
    backgroundColor: colors.backgroundElevated,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    padding: spacing.md,
    gap: spacing.xs,
  },
  inlineAdjust: {
    marginBottom: spacing.sm,
    gap: spacing.xs,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    backgroundColor: colors.background,
  },
  cardTitle: {
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.semibold,
    color: colors.foreground,
    flexShrink: 1,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  roleBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
  },
  roleBadgeText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
  },
  admin: {
    marginTop: spacing.lg,
  },
  adjust: {
    marginTop: spacing.md,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  chipRowNowrap: {
    flexWrap: "nowrap",
    marginBottom: 0,
    paddingBottom: spacing.xs,
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.background,
  },
  chipSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  chipLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.foreground,
  },
  chipLabelSelected: {
    color: colors.accentContrast,
    fontWeight: typography.fontWeight.semibold,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
    color: colors.foreground,
    backgroundColor: colors.background,
    minHeight: 44,
  },
  csvInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  excelCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colors.background,
    gap: spacing.xs,
  },
  excelActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  button: {
    marginTop: spacing.sm,
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    minHeight: 44,
    justifyContent: "center",
  },
  disabled: {
    opacity: 0.6,
  },
  buttonLabel: {
    color: colors.accentContrast,
    fontWeight: typography.fontWeight.semibold,
  },
  inlineLabel: {
    fontSize: typography.fontSize.sm,
    color: colors.muted,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  priceRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  priceInputCompact: {
    width: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    color: colors.foreground,
    backgroundColor: colors.background,
    minHeight: 32,
    textAlign: "center",
    fontSize: typography.fontSize.sm,
  },
  playerTable: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    overflow: "hidden",
    backgroundColor: colors.background,
  },
  playerHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.backgroundSubtle,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  playerHeaderCell: {
    fontSize: typography.fontSize.xs,
    color: colors.foregroundMuted,
    fontWeight: typography.fontWeight.semibold,
  },
  playerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    minHeight: 40,
  },
  playerNameCell: {
    flex: 1.4,
    minWidth: 0,
  },
  playerClubCell: {
    flex: 1,
    minWidth: 0,
  },
  playerCreditsCell: {
    minWidth: 52,
    flexShrink: 0,
  },
  playerSlotCell: {
    width: 28,
    flexShrink: 0,
    textAlign: "center",
  },
  playerActionCell: {
    width: 28,
    flexShrink: 0,
  },
  listoneRoleCell: {
    width: 28,
    flexShrink: 0,
  },
  listoneNameCell: {
    flex: 1.2,
    minWidth: 0,
  },
  listoneClubCell: {
    flex: 0.8,
    minWidth: 0,
  },
  listoneStatusCell: {
    flex: 1.1,
    minWidth: 0,
  },
  listoneStatusFree: {
    fontSize: typography.fontSize.xs,
    color: colors.success,
  },
  listoneStatusOwned: {
    fontSize: typography.fontSize.xs,
    color: colors.warning,
  },
  playerName: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.foreground,
  },
  playerClub: {
    fontSize: typography.fontSize.xs,
    color: colors.foregroundMuted,
  },
  rowActionBadge: {
    width: 28,
    height: 28,
    borderRadius: radius.pill,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  rowActionAssign: {
    backgroundColor: colors.accent,
  },
  rowActionRelease: {
    backgroundColor: colors.danger,
  },
  priceInput: {
    width: 88,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.foreground,
    backgroundColor: colors.background,
    minHeight: 40,
    textAlign: "center",
  },
  compactButton: {
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  ghostButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
    backgroundColor: colors.background,
  },
  ghostButtonLabel: {
    color: colors.foreground,
    fontWeight: typography.fontWeight.semibold,
    fontSize: typography.fontSize.sm,
  },
  statusFree: {
    fontSize: typography.fontSize.sm,
    color: colors.success,
    marginBottom: spacing.xs,
  },
  statusOwned: {
    fontSize: typography.fontSize.sm,
    color: colors.warning,
    marginBottom: spacing.xs,
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  ok: {
    fontSize: typography.fontSize.sm,
    color: colors.foreground,
    marginTop: spacing.sm,
  },
  error: {
    fontSize: typography.fontSize.sm,
    color: colors.danger,
    marginTop: spacing.sm,
  },
}));
