"""Shared SQLAlchemy column types."""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import DateTime, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import TypeDecorator


class UTCDateTime(TypeDecorator[datetime]):
    """Store aware UTC timestamps as PostgreSQL ``timestamptz``."""

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: object) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: object) -> datetime | None:
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)


def uuid_pk_column() -> Mapped:
    """Primary key UUID generated by PostgreSQL ``gen_random_uuid()``."""

    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def utc_now_column(name: str, *, nullable: bool = False) -> Mapped:
    """``timestamptz`` column defaulting to UTC ``now()``."""

    return mapped_column(
        UTCDateTime(),
        name=name,
        nullable=nullable,
        server_default=text("timezone('utc', now())"),
    )
